#!/bin/bash -eu
# SPDX-FileCopyrightText: 2025 Uwe Fechner
# SPDX-License-Identifier: MIT

rm -rf /tmp/testdepot
mkdir /tmp/testdepot
rm -rf /tmp/test
mkdir /tmp/test
cd /tmp/test
export JULIA_DEPOT_PATH=/tmp/testdepot 
mkdir test 
cd test
julia --project=. -e 'using Pkg; Pkg.add(Pkg.PackageSpec(name="KiteModels", rev="main"))'
julia --project -e 'using KiteModels; KiteModels.install_examples()'
if [[ ! -x ./bin/create_sys_image ]]; then
	echo "Error: expected executable ./bin/create_sys_image after install_examples()."
	exit 1
fi
./bin/create_sys_image -y
