#!/bin/bash -eu
# SPDX-FileCopyrightText: 2025 Uwe Fechner
# SPDX-License-Identifier: MIT

rm -rf /tmp/testdepot
mkdir /tmp/testdepot
rm -rf /tmp/test
mkdir /tmp/test
cd /tmp/test
export JULIA_DEPOT_PATH=/tmp/testdepot 
export JULIA_PKG_SERVER_REGISTRY_PREFERENCE=eager
mkdir test 
cd test
julia --project=. -e 'using Pkg; Pkg.add("KiteModels")'
julia --project -e 'using KiteModels; KiteModels.install_examples()'
echo "Creating the system image..."
./bin/create_sys_image
