name: Daily Script

on:
  schedule:
    - cron: '0 2 * * *'   # Runs every day at 2am UTC
  workflow_dispatch:      # Allows manual trigger from the Actions tab

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install mesa
        run: sudo apt-get update && sudo apt-get install -y xorg-dev mesa-utils xvfb libgl1 freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
      - name: Run your script
        run: |
          DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' ./scripts/run_test
